// Generated by Selenium IDE
// import org.junit.Test;
// import org.junit.Before;
// import org.junit.After;
// import static org.junit.Assert.*;
// import static org.hamcrest.CoreMatchers.is;
// import static org.hamcrest.core.IsNot.not;
// import org.openqa.selenium.By;
// import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
// import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.remote.RemoteWebDriver;
// import org.openqa.selenium.remote.DesiredCapabilities;
// import org.openqa.selenium.Dimension;
// import org.openqa.selenium.WebElement;
// import org.openqa.selenium.interactions.Actions;
// import org.openqa.selenium.support.ui.ExpectedConditions;
// import org.openqa.selenium.support.ui.WebDriverWait;
// import org.openqa.selenium.JavascriptExecutor;
// import org.openqa.selenium.Alert;
// import org.openqa.selenium.Keys;
// import java.util.*;
// import java.net.MalformedURLException;
// import java.net.URL;
// public class PurchaseTestTest {
//   private WebDriver driver;
//   private Map<String, Object> vars;
//   JavascriptExecutor js;
//   @Before
//   public void setUp() {
//     driver = new ChromeDriver();
//     js = (JavascriptExecutor) driver;
//     vars = new HashMap<String, Object>();
//   }
//   @After
//   public void tearDown() {
//     driver.quit();
//   }
//   @Test
//   public void purchaseTest() {
//     driver.get("https://blazedemo.com/");
// {
//     WebElement dropdown = driver.findElement(By.name("fromPort"));
//     dropdown.findElement(By.xpath("//option[. = 'San Diego']")).click();
//   }
//   {
//     WebElement element = driver.findElement(By.name("fromPort"));
//     Actions builder = new Actions(driver);
//     builder.moveToElement(element).clickAndHold().perform();
//   }
//   {
//     WebElement element = driver.findElement(By.name("fromPort"));
//     Actions builder = new Actions(driver);
//     builder.moveToElement(element).perform();
//   }
//   {
//     WebElement element = driver.findElement(By.name("fromPort"));
//     Actions builder = new Actions(driver);
//     builder.moveToElement(element).release().perform();
//   }
//   {
//     WebElement dropdown = driver.findElement(By.name("toPort"));
//     dropdown.findElement(By.xpath("//option[. = 'Berlin']")).click();
//   }
//   {
//     WebElement element = driver.findElement(By.name("toPort"));
//     Actions builder = new Actions(driver);
//     builder.moveToElement(element).clickAndHold().perform();
//   }
//   {
//     WebElement element = driver.findElement(By.name("toPort"));
//     Actions builder = new Actions(driver);
//     builder.moveToElement(element).perform();
//   }
//   {
//     WebElement element = driver.findElement(By.name("toPort"));
//     Actions builder = new Actions(driver);
//     builder.moveToElement(element).release().perform();
//   }
//   driver.findElement(By.cssSelector(".btn-primary")).click();
//   driver.findElement(By.cssSelector("tr:nth-child(5) .btn")).click();
//   driver.findElement(By.cssSelector(".control-group:nth-child(2) > .controls")).click();
//   driver.findElement(By.id("inputName")).click();
//   driver.findElement(By.id("inputName")).sendKeys("vjovlwdkv");
//   driver.findElement(By.id("address")).click();
//   driver.findElement(By.id("address")).sendKeys("fwvwrvwr");
//   driver.findElement(By.id("city")).click();
//   driver.findElement(By.id("city")).sendKeys("efwr");
//   driver.findElement(By.id("state")).click();
//   driver.findElement(By.id("state")).sendKeys("wvvwr");
//   driver.findElement(By.id("zipCode")).click();
//   driver.findElement(By.id("zipCode")).sendKeys("1243");
//   driver.findElement(By.id("creditCardNumber")).click();
//   driver.findElement(By.id("creditCardNumber")).sendKeys("23456");
//   driver.findElement(By.id("creditCardMonth")).click();
//   driver.findElement(By.id("creditCardMonth")).sendKeys("10");
//   driver.findElement(By.id("creditCardYear")).click();
//   driver.findElement(By.id("creditCardYear")).sendKeys("2023");
//   driver.findElement(By.id("nameOnCard")).click();
//   driver.findElement(By.id("nameOnCard")).sendKeys("srdtfyhi");
//   driver.findElement(By.cssSelector(".btn-primary")).click();
//   }
// }


import org.junit.Before;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import io.github.bonigarcia.wdm.WebDriverManager;


@ExtendWith(SeleniumJupiter.class)
public class PurchaseTestTest {
    WebDriver driver;

    @Test
    public void purchaseTest() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();  
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        driver.get("https://blazedemo.com/");

        {
            WebElement dropdown = driver.findElement(By.name("fromPort"));
            dropdown.findElement(By.xpath("//option[. = 'San Diego']")).click();
          }
          {
            WebElement element = driver.findElement(By.name("fromPort"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
          }
          {
            WebElement element = driver.findElement(By.name("fromPort"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
          }
          {
            WebElement element = driver.findElement(By.name("fromPort"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
          }
          {
            WebElement dropdown = driver.findElement(By.name("toPort"));
            dropdown.findElement(By.xpath("//option[. = 'Berlin']")).click();
          }
          {
            WebElement element = driver.findElement(By.name("toPort"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
          }
          {
            WebElement element = driver.findElement(By.name("toPort"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
          }
          {
            WebElement element = driver.findElement(By.name("toPort"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
          }
          driver.findElement(By.cssSelector(".btn-primary")).click();
          driver.findElement(By.cssSelector("tr:nth-child(5) .btn")).click();
          driver.findElement(By.cssSelector(".control-group:nth-child(2) > .controls")).click();
          driver.findElement(By.id("inputName")).click();
          driver.findElement(By.id("inputName")).sendKeys("vjovlwdkv");
          driver.findElement(By.id("address")).click();
          driver.findElement(By.id("address")).sendKeys("fwvwrvwr");
          driver.findElement(By.id("city")).click();
          driver.findElement(By.id("city")).sendKeys("efwr");
          driver.findElement(By.id("state")).click();
          driver.findElement(By.id("state")).sendKeys("wvvwr");
          driver.findElement(By.id("zipCode")).click();
          driver.findElement(By.id("zipCode")).sendKeys("1243");
          driver.findElement(By.id("creditCardNumber")).click();
          driver.findElement(By.id("creditCardNumber")).sendKeys("23456");
          driver.findElement(By.id("creditCardMonth")).click();
          driver.findElement(By.id("creditCardMonth")).sendKeys("10");
          driver.findElement(By.id("creditCardYear")).click();
          driver.findElement(By.id("creditCardYear")).sendKeys("2023");
          driver.findElement(By.id("nameOnCard")).click();
          driver.findElement(By.id("nameOnCard")).sendKeys("srdtfyhi");
          driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.quit();
        }      

}
